name = "cvcManual"
defaultTargets = ["textbook"]

[[require]]
scope = "leanprover"
name = "verso"

[[require]]
name = "cvc"
path = ".."

[[lean_lib]]
name = "Manual"
root = "Manual"

[[lean_exe]]
name = "textbook"
root = "Main"
