name: CI

on:
  push:
    branches: ["cleanup"]
  pull_request:
    branches: ["cleanup"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      # uses lean standard action with all default input values
      - uses: leanprover/lean-action@v1
        with:
          lint: "false"